// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt0yhm9l6tYyf_nmVRclnoOXFM-brKSpQ',
    appId: '1:515281116408:web:e6151061ae3fd382e76f0d',
    messagingSenderId: '515281116408',
    projectId: 'meu-buteco-c7afd',
    authDomain: 'meu-buteco-c7afd.firebaseapp.com',
    storageBucket: 'meu-buteco-c7afd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwsCh9F5xFAUnkEMvACpEzdbUxzErZwdQ',
    appId: '1:515281116408:android:9aa9e885828d5128e76f0d',
    messagingSenderId: '515281116408',
    projectId: 'meu-buteco-c7afd',
    storageBucket: 'meu-buteco-c7afd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ51-05tbS_xqs98inkSD5sBWTDKDX5sA',
    appId: '1:515281116408:ios:b560c49d9dd365ffe76f0d',
    messagingSenderId: '515281116408',
    projectId: 'meu-buteco-c7afd',
    storageBucket: 'meu-buteco-c7afd.firebasestorage.app',
    iosBundleId: 'com.example.meuButeco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ51-05tbS_xqs98inkSD5sBWTDKDX5sA',
    appId: '1:515281116408:ios:b560c49d9dd365ffe76f0d',
    messagingSenderId: '515281116408',
    projectId: 'meu-buteco-c7afd',
    storageBucket: 'meu-buteco-c7afd.firebasestorage.app',
    iosBundleId: 'com.example.meuButeco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt0yhm9l6tYyf_nmVRclnoOXFM-brKSpQ',
    appId: '1:515281116408:web:4ba9ff18af2ea89ce76f0d',
    messagingSenderId: '515281116408',
    projectId: 'meu-buteco-c7afd',
    authDomain: 'meu-buteco-c7afd.firebaseapp.com',
    storageBucket: 'meu-buteco-c7afd.firebasestorage.app',
  );
}
